[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.buildArgs]
AI_MODE = "full"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"